Django_lv_5/urls.py
from django.contrib import admin
from django.urls import path, include

from web_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('web_app/', include('web_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.speciaḷ̣̣̣̣̣, name='special'),
]

web_app/urls.py
# Template url
from django.conf.urls import url

from web_app import views

app_name = 'web_app'

urlpatterns = [
    url('register/', views.register, name='register'),
    url('user_login/', views.user_login, name='user_login'),
]

web_app/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

web_app/forms.py
from django import forms
from django.contrib.auth.models import User

from web_app.models import Profile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('portfolio_site', 'profile_pic')

web_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from web_app.forms import UserForm, ProfileForm


# Create your views here.


def index(request):
    return render(request, 'web_app/index.html')


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = ProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = ProfileForm()

    return render(request, 'web_app/registration.html',
                  {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('ACCOUNT IS NOT ACTIVE')

        else:
            print('Someone tried to login and failed!')
            print('Username: {} \n Password: {}'.format(username, password))

            return HttpResponse('INVALID LOGIN DETAIL SUPPLIED!')

    else:
        return render(request, 'web_app/login_v1.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required()
def speciaḷ̣̣̣̣̣(request):
    return HttpResponse('Logged in successfully!')

templates/web_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">

	<link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
	<script src={% static 'js/bootstrap.min.js' %}></script>

	<title></title>
</head>
<body>
	{#	Navbar#}
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="#">Navbar</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
		        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		{#		Navbar's sections#}
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">

				<li class="nav-item active">
					<a class="nav-link" href={% url 'index' %}>Index <span class="sr-only">(current)</span></a>
				</li>

				<li class="nav-item active">
					<a class="nav-link" href={% url 'admin:index' %}>Admin <span class="sr-only">(current)</span></a>
				</li>

				<li class="nav-item active">
					<a class="nav-link" href={% url 'web_app:register' %}>Register <span
							class="sr-only">(current)</span></a>
				</li>
			</ul>
		</div>

		{#Set navbar's items to the right#}
		<div class="navbar-collapse collapse ">
			<ul class="navbar-nav ml-auto">
				{% if user.is_authenticated %}
					<li class="nav-item active">
						<a class="btn btn-danger btn-lg" href={% url 'logout' %} role="button">Log out</a>
					</li>

				{% else %}
					<li class="nav-item active">
						<a class="btn btn-primary btn-lg" href={% url 'web_app:user_login' %} role="button">Log in</a>
					</li>
				{% endif %}
			</ul>
		</div>
	</nav>

	<div class="container">
		{% block body_block %}
			{#			HTML will go in here#}
		{% endblock %}
	</div>

</body>
</html>

templates/web_app/index.html
<!DOCTYPE html>
{% extends 'web_app/base.html' %}

{% block body_block %}
	<div class="jumbotron">
		<h1 class="display-4">INDEX PAGE</h1>
		<p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to
			featured content or information.</p>
		<hr class="my-4">
		<p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
		<a class="btn btn-primary btn-lg" href={% url 'web_app:register' %} role="button">Register</a>
	</div>

{% endblock %}

templates/web_app/landing_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Grayscale - Start Bootstrap Theme</title>

	<!-- Bootstrap core CSS -->
	<link href={% static 'grayscale/vendor/bootstrap/css/bootstrap.min.css' %} rel="stylesheet">

	<!-- Custom fonts for this template -->
	<link href={% static 'grayscale/vendor/fontawesome-free/css/all.min.css' %} rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
	      rel="stylesheet">

	<!-- Custom styles for this template -->
	<link href={% static 'grayscale/css/grayscale.min.css' %} rel="stylesheet">

</head>

<body id="page-top">

	<!-- Navigation -->
	<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
		<div class="container">
			<a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a>
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
			        data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
			        aria-label="Toggle navigation">
				Menu
				<i class="fas fa-bars"></i>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<a class="nav-link js-scroll-trigger" href="#about">About</a>
					</li>
					<li class="nav-item">
						<a class="nav-link js-scroll-trigger" href="#projects">Projects</a>
					</li>
					<li class="nav-item">
						<a class="nav-link js-scroll-trigger" href="#signup">Contact</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<!-- Header -->
	<header class="masthead">
		<div class="container d-flex h-100 align-items-center">
			<div class="mx-auto text-center">
				<h1 class="mx-auto my-0 text-uppercase">Grayscale</h1>
				<h2 class="text-white-50 mx-auto mt-2 mb-5">A free, responsive, one page Bootstrap theme created by
					Start Bootstrap.</h2>
				<a href="#about" class="btn btn-primary js-scroll-trigger">Get Started</a>
			</div>
		</div>
	</header>

	<!-- About Section -->
	<section id="about" class="about-section text-center">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 mx-auto">
					<h2 class="text-white mb-4">Built with Bootstrap 4</h2>
					<p class="text-white-50">Grayscale is a free Bootstrap theme created by Start Bootstrap. It can be
						yours right now, simply download the template on
						<a href="http://startbootstrap.com/template-overviews/grayscale/">the preview page</a>. The
						theme is open source, and you can use it for any purpose, personal or commercial.</p>
				</div>
			</div>
			<img src="img/ipad.png" class="img-fluid" alt="">
		</div>
	</section>

	<!-- Projects Section -->
	<section id="projects" class="projects-section bg-light">
		<div class="container">

			<!-- Featured Project Row -->
			<div class="row align-items-center no-gutters mb-4 mb-lg-5">
				<div class="col-xl-8 col-lg-7">
					<img class="img-fluid mb-3 mb-lg-0" src="img/bg-masthead.jpg" alt="">
				</div>
				<div class="col-xl-4 col-lg-5">
					<div class="featured-text text-center text-lg-left">
						<h4>Shoreline</h4>
						<p class="text-black-50 mb-0">Grayscale is open source and MIT licensed. This means you can use
							it for any project - even commercial projects! Download it, customize it, and publish your
							website!</p>
					</div>
				</div>
			</div>

			<!-- Project One Row -->
			<div class="row justify-content-center no-gutters mb-5 mb-lg-0">
				<div class="col-lg-6">
					<img class="img-fluid" src="img/demo-image-01.jpg" alt="">
				</div>
				<div class="col-lg-6">
					<div class="bg-black text-center h-100 project">
						<div class="d-flex h-100">
							<div class="project-text w-100 my-auto text-center text-lg-left">
								<h4 class="text-white">Misty</h4>
								<p class="mb-0 text-white-50">An example of where you can put an image of a project, or
									anything else, along with a description.</p>
								<hr class="d-none d-lg-block mb-0 ml-0">
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Project Two Row -->
			<div class="row justify-content-center no-gutters">
				<div class="col-lg-6">
					<img class="img-fluid" src="img/demo-image-02.jpg" alt="">
				</div>
				<div class="col-lg-6 order-lg-first">
					<div class="bg-black text-center h-100 project">
						<div class="d-flex h-100">
							<div class="project-text w-100 my-auto text-center text-lg-right">
								<h4 class="text-white">Mountains</h4>
								<p class="mb-0 text-white-50">Another example of a project with its respective
									description. These sections work well responsively as well, try this theme on a
									small screen!</p>
								<hr class="d-none d-lg-block mb-0 mr-0">
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</section>

	<!-- Signup Section -->
	<section id="signup" class="signup-section">
		<div class="container">
			<div class="row">
				<div class="col-md-10 col-lg-8 mx-auto text-center">

					<i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
					<h2 class="text-white mb-5">Subscribe to receive updates!</h2>

					<form class="form-inline d-flex">
						<input type="email" class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0" id="inputEmail"
						       placeholder="Enter email address...">
						<button type="submit" class="btn btn-primary mx-auto">Subscribe</button>
					</form>

				</div>
			</div>
		</div>
	</section>

	<!-- Contact Section -->
	<section class="contact-section bg-black">
		<div class="container">

			<div class="row">

				<div class="col-md-4 mb-3 mb-md-0">
					<div class="card py-4 h-100">
						<div class="card-body text-center">
							<i class="fas fa-map-marked-alt text-primary mb-2"></i>
							<h4 class="text-uppercase m-0">Address</h4>
							<hr class="my-4">
							<div class="small text-black-50">4923 Market Street, Orlando FL</div>
						</div>
					</div>
				</div>

				<div class="col-md-4 mb-3 mb-md-0">
					<div class="card py-4 h-100">
						<div class="card-body text-center">
							<i class="fas fa-envelope text-primary mb-2"></i>
							<h4 class="text-uppercase m-0">Email</h4>
							<hr class="my-4">
							<div class="small text-black-50">
								<a href="#">hello@yourdomain.com</a>
							</div>
						</div>
					</div>
				</div>

				<div class="col-md-4 mb-3 mb-md-0">
					<div class="card py-4 h-100">
						<div class="card-body text-center">
							<i class="fas fa-mobile-alt text-primary mb-2"></i>
							<h4 class="text-uppercase m-0">Phone</h4>
							<hr class="my-4">
							<div class="small text-black-50">+1 (555) 902-8832</div>
						</div>
					</div>
				</div>
			</div>

			<div class="social d-flex justify-content-center">
				<a href="#" class="mx-2">
					<i class="fab fa-twitter"></i>
				</a>
				<a href="#" class="mx-2">
					<i class="fab fa-facebook-f"></i>
				</a>
				<a href="#" class="mx-2">
					<i class="fab fa-github"></i>
				</a>
			</div>

		</div>
	</section>

	<!-- Footer -->
	<footer class="bg-black small text-center text-white-50">
		<div class="container">
			Copyright &copy; Your Website 2019
		</div>
	</footer>

	<!-- Bootstrap core JavaScript -->
	<script src={% static 'grayscale/vendor/jquery/jquery.min.js' %}></script>
	<script src={% static 'grayscale/vendor/bootstrap/js/bootstrap.bundle.min.js' %}></script>

	<!-- Plugin JavaScript -->
	<script src={% static 'grayscale/vendor/jquery-easing/jquery.easing.min.js' %}></script>

	<!-- Custom scripts for this template -->
	<script src={% static 'grayscale/js/grayscale.min.js' %}></script>

</body>

</html>

templates/web_app/login.html
<!DOCTYPE html>

{% extends 'web_app/base.html' %}

{% block body_block %}
	<div class="jumbotron">
		<h1 class="display-4">LOGIN PAGE</h1>
		<hr class="my-4">

		<form action={% url 'web_app:user_login' %} method="post">
			{% csrf_token %}

						Username
			<div class="form-group">
				<label for="exampleInputEmail1">Username</label>
				<input type="text" class="form-control" name="username" aria-describedby="emailHelp">
			</div>

						Password
			<div class="form-group">
				<label for="exampleInputPassword1">Password</label>
				<input type="password" class="form-control" name="password">
			</div>

						Submit
			<button type="submit" class="btn btn-primary">Log in</button>
		</form>

	</div>

{% endblock %}

templates/web_app/login_v1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Login V1</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
	<link rel="icon" type="image/png" href={% static "Login_v1/images/icons/favicon.ico" %}/>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static "Login_v1/vendor/bootstrap/css/bootstrap.min.css" %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static "Login_v1/fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static "Login_v1/vendor/animate/animate.css" %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static "Login_v1/vendor/css-hamburgers/hamburgers.min.css" %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static "Login_v1/vendor/select2/select2.min.css" %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static "Login_v1/css/util.css" %}>
	<link rel="stylesheet" type="text/css" href={% static "Login_v1/css/main.css" %}>
	<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src={% static "Login_v1/images/img-01.png" %} alt="IMG">
				</div>

				{#				Main form#}
				<form class="login100-form validate-form" action={% url 'web_app:user_login' %} method="post">
					{% csrf_token %}

					<span class="login100-form-title">
						Member Login
					</span>

					<div class="wrap-input100 validate-input" data-validate="Username doesn't exist">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>

					<div class="container-login100-form-btn">
						<button type="submit" class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href={% url 'web_app:register' %}>
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>

			</div>
		</div>
	</div>


	<!--===============================================================================================-->
	<script src={% static "Login_v1/vendor/jquery/jquery-3.2.1.min.js" %}></script>
	<!--===============================================================================================-->
	<script src={% static "Login_v1/vendor/bootstrap/js/popper.js" %}></script>
	<script src={% static "Login_v1/vendor/bootstrap/js/bootstrap.min.js" %}></script>
	<!--===============================================================================================-->
	<script src={% static "Login_v1/vendor/select2/select2.min.js" %}></script>
	<!--===============================================================================================-->
	<script src={% static "Login_v1/vendor/tilt/tilt.jquery.min.js" %}></script>
	<script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
	</script>
	<!--===============================================================================================-->
	<script src={% static "Login_v1/js/main.js" %}></script>

</body>
</html>

templates/web_app/registration.html
<!DOCTYPE html>
{% extends 'web_app/base.html' %}
{% load static %}

{% block body_block %}
	<div class="jumbotron">
		<h1 class="display-4">REGISTER PAGE</h1>
		<hr class="my-4">

		{#Form#}
		{% if registered %}
			<h1 class="display-4">Thank you!</h1>

		{% else %}
			<form enctype="multipart/form-data" method="post">
				{% csrf_token %}

				{{ user_form.as_p }}
				{{ profile_form.as_p }}

				<button type="submit" class="btn btn-primary">Register!</button>
			</form>
		{% endif %}
	</div>

{% endblock %}